const ScheduleActionTypes = {
  FETCH_BOOKINGS_START: 'FETCH_BOOKINGS_START',
  FETCH_BOOKINGS_SUCCESS: 'FETCH_BOOKINGS_SUCCESS',
  FETCH_BOOKINGS_FAILURE: 'FETCH_BOOKINGS_FAILURE',
  FETCH_ROOMS_START: 'FETCH_ROOMS_START',
  FETCH_ROOMS_SUCCESS: 'FETCH_ROOMS_SUCCESS',
  FETCH_ROOMS_FAILURE: 'FETCH_ROOMS_FAILURE',
};

export default ScheduleActionTypes;
